import { SRD_ATTRIBUTION } from "../../src/data/srd/attribution";
import { GAP_CODES } from "../../src/data/srd/monsters/gaps";
import { MONSTER_OVERRIDES } from "../../src/data/srd/monsters/overrides";
import type { SrdMonsterIndexEntry } from "../../src/data/srd/monsters/types";
import { parseCsv } from "./csv";
import { splitForms } from "./forms";
import { parseMonster, type ParsedMonster } from "./monster";
import { validateMonster } from "./validate";

// One source of truth for the statement (verbatim from the SRD 5.1's own Legal Information page).
export const ATTRIBUTION = SRD_ATTRIBUTION;

export interface MonsterLibraryBuild {
  parsed: ParsedMonster[];
  /** Output path (relative to `src/data/srd/monsters/generated`) → file contents. */
  files: Map<string, string>;
  errors: string[];
  warnings: string[];
}

/** Whole pipeline: CSV text → parsed creatures → validated → the files to write. Pure; no I/O. */
export function buildMonsterLibrary(csvText: string): MonsterLibraryBuild {
  const rows = parseCsv(csvText);
  const parsed: ParsedMonster[] = [];
  const errors: string[] = [];
  const warnings: string[] = [];

  for (const row of rows) {
    const monster = parseMonster(row);
    const override = MONSTER_OVERRIDES[monster.slug];
    if (override) {
      if (override.patch) monster.definition = override.patch(monster.definition);
      const cleared = new Set(override.clearGaps ?? []);
      monster.gapNotes = monster.gapNotes.filter((gap) => !cleared.has(gap.code));
      monster.gapNotes.push(...(override.addGaps ?? []));
      monster.gaps = [...new Set(monster.gapNotes.map((gap) => gap.code))].sort();
    }
    for (const piece of splitForms(monster)) {
      const result = validateMonster(piece.definition);
      errors.push(...result.errors);
      warnings.push(...result.warnings);
      parsed.push(piece);
    }
  }
  for (const slug of Object.keys(MONSTER_OVERRIDES)) {
    if (!parsed.some((monster) => monster.slug === slug)) errors.push(`override for unknown monster "${slug}"`);
  }
  const ids = new Set<string>();
  for (const monster of parsed) {
    if (ids.has(monster.definition.id)) errors.push(`duplicate monster id ${monster.definition.id}`);
    ids.add(monster.definition.id);
  }

  parsed.sort((a, b) => a.definition.name.localeCompare(b.definition.name));

  const files = new Map<string, string>();
  const byType = new Map<string, ParsedMonster[]>();
  for (const monster of parsed) {
    const chunk = monster.definition.type ?? "unknown";
    byType.set(chunk, [...(byType.get(chunk) ?? []), monster]);
  }
  for (const [chunk, monsters] of [...byType.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const body = monsters.map((monster) => `  ${JSON.stringify(monster.definition)}`).join(",\n");
    files.set(`chunks/${chunk}.json`, `{\n "attribution": ${JSON.stringify(ATTRIBUTION)},\n "definitions": [\n${body}\n ]\n}\n`);
  }

  const index: SrdMonsterIndexEntry[] = parsed.map((monster) => {
    const d = monster.definition;
    return {
      id: d.id,
      slug: monster.slug,
      name: d.name,
      type: d.type!,
      size: d.size,
      cr: d.challengeRating ?? 0,
      xp: monster.meta.xp,
      hp: d.maxHp,
      ac: d.armorClass,
      speed: d.movement ?? { walk: d.speed },
      ...(monster.meta.family ? { family: monster.meta.family } : {}),
      environments: d.environments ?? [],
      legendary: monster.meta.legendary,
      spellcaster: monster.meta.spellcaster,
      hidden: d.hidden === true,
      tier: monster.tier,
      gaps: monster.gaps,
      chunk: d.type!
    };
  });
  files.set("monster-index.json", `{\n "attribution": ${JSON.stringify(ATTRIBUTION)},\n "monsters": [\n${index.map((entry) => `  ${JSON.stringify(entry)}`).join(",\n")}\n ]\n}\n`);

  const tiers = { full: 0, partial: 0, manual: 0 };
  const gapCounts = new Map<string, number>();
  for (const monster of parsed) {
    tiers[monster.tier] += 1;
    for (const code of monster.gaps) gapCounts.set(code, (gapCounts.get(code) ?? 0) + 1);
  }
  const report: string[] = [];
  report.push("# SRD monster coverage", "", "_Generated by `npm run srd:monsters` — do not edit._", "");
  report.push(`${parsed.length} creatures — **${tiers.full} full**, **${tiers.partial} partial**, **${tiers.manual} manual**.`, "");
  report.push("## Gap codes", "", "A phase is done when its codes reach 0.", "", "| Code | Creatures | Meaning |", "|---|---:|---|");
  for (const [code, meaning] of Object.entries(GAP_CODES)) {
    report.push(`| \`${code}\` | ${gapCounts.get(code) ?? 0} | ${meaning} |`);
  }
  report.push("", "## Parser warnings", "", warnings.length === 0 ? "None." : `${warnings.length} (review; not errors):`, "");
  for (const message of warnings) report.push(`- ${message}`);
  report.push("", "## Creatures", "", "| Creature | CR | Tier | Gaps |", "|---|---:|---|---|");
  for (const monster of parsed) {
    report.push(`| ${monster.definition.name} | ${monster.definition.challengeRating} | ${monster.tier} | ${monster.gaps.join(", ")} |`);
  }
  report.push("", "## Gap detail", "");
  for (const monster of parsed) {
    if (monster.gapNotes.length === 0) continue;
    report.push(`### ${monster.definition.name}`);
    for (const gap of monster.gapNotes) report.push(`- \`${gap.code}\` — ${gap.note}`);
    report.push("");
  }
  files.set("../COVERAGE.md", `${report.join("\n")}\n`);

  return { parsed, files, errors, warnings };
}
