/**
 * The coverage audit (`src/data/srd/2024/coverage.ts`) checked against the SRD 5.2 reference data, and rendered as
 * `COVERAGE.md`. Pure; no I/O.
 */
import {
  CLASS_COVERAGE,
  FEAT_COVERAGE,
  GAPS,
  SPECIES_COVERAGE,
  type CoverageEntry,
  type GapCode,
  type Verdict
} from "../../src/data/srd/2024/coverage";
import type { ReferenceClass, Srd2024Reference } from "../../src/data/srd/2024/reference-types";

const PREFIX = "srd-2024_";
const VERDICTS: Verdict[] = ["full", "partial", "manual", "builder", "info"];

const bare = (key: string) => (key.startsWith(PREFIX) ? key.slice(PREFIX.length) : key);
const traitSlug = (name: string) => name.toLowerCase().replace(/[’']/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
export const speciesTraitKey = (speciesKey: string, traitName: string) => `${bare(speciesKey)}:${traitSlug(traitName)}`;

/** Every feature, feat and trait with a verdict, every verdict for something that exists. */
export function checkCoverage(reference: Srd2024Reference): string[] {
  const errors: string[] = [];
  const compare = (what: string, keys: string[], audit: Record<string, CoverageEntry>) => {
    const known = new Set(keys);
    for (const key of keys) if (!audit[key]) errors.push(`${what} ${key} has no verdict in coverage.ts`);
    for (const key of Object.keys(audit)) if (!known.has(key)) errors.push(`coverage.ts has a verdict for ${what} ${key}, which isn't in the reference`);
    for (const [key, entry] of Object.entries(audit)) {
      if ((entry.verdict === "partial" || entry.verdict === "manual") && !entry.gaps?.length) errors.push(`${what} ${key} is ${entry.verdict} but names no gap`);
      for (const gap of entry.gaps ?? []) if (!(gap in GAPS)) errors.push(`${what} ${key} names an unknown gap ${gap}`);
    }
  };
  compare("feature", reference.classes.flatMap((entry) => entry.features.map((feature) => bare(feature.key))), CLASS_COVERAGE);
  compare("feat", reference.feats.map((feat) => bare(feat.key)), FEAT_COVERAGE);
  compare("trait", reference.species.flatMap((species) => species.traits.map((trait) => speciesTraitKey(species.key, trait.name))), SPECIES_COVERAGE);
  return errors;
}

const cell = (text: string) => text.replace(/\|/g, "\\|").replace(/\n+/g, " ");
const gapList = (gaps: GapCode[] | undefined) => (gaps?.length ? gaps.map((gap) => `\`${gap}\``).join(", ") : "");

function counts(entries: CoverageEntry[]): Record<Verdict, number> {
  const tally = Object.fromEntries(VERDICTS.map((verdict) => [verdict, 0])) as Record<Verdict, number>;
  for (const entry of entries) tally[entry.verdict] += 1;
  return tally;
}

interface GapUse {
  classes: Set<string>;
  features: string[];
  firstLevel: number;
}

export function renderCoverage(reference: Srd2024Reference): string {
  const classes = reference.classes.filter((entry) => !entry.subclassOf);
  const subclassesOf = (key: string) => reference.classes.filter((entry) => entry.subclassOf === key);
  const lines: string[] = [];
  const line = (text = "") => lines.push(text);

  line("# 2024 rules coverage (SRD 5.2)");
  line();
  line("Generated by `npm run srd:2024` from `coverage.ts` and the SRD 5.2 reference data (`generated/reference.json`). Don't");
  line("edit it by hand: change a verdict in `coverage.ts` and regenerate. See PC_BUILDER_PLAN.md, Phase 0.");
  line();
  line("What the character builder can do with each 2024 class and subclass feature, feat and species trait. The builder");
  line("adds every feature whatever its verdict: one the engine can't run goes on the actor as reference text, tagged with");
  line("its gaps, never dropped and never approximated without saying so.");
  line();
  line("- **full**: runs with what the engine has today. **partial**: some of it runs; the note says what doesn't.");
  line("- **manual**: doesn't run; it's on the actor for the DM. **builder**: the builder does it (scores, proficiencies,");
  line("  skills, speed, hit points, spells, choices, pools). **info**: nothing to do in a fight.");
  line();

  // Summary
  line("## Summary");
  line();
  line("| | Features | Full | Partial | Manual | Builder | Info |");
  line("|---|---|---|---|---|---|---|");
  const row = (label: string, entries: CoverageEntry[]) => {
    const tally = counts(entries);
    line(`| ${label} | ${entries.length} | ${tally.full} | ${tally.partial} | ${tally.manual} | ${tally.builder} | ${tally.info} |`);
  };
  const classEntries = (entry: ReferenceClass) =>
    [entry, ...subclassesOf(entry.key)].flatMap((owner) => owner.features.map((feature) => CLASS_COVERAGE[bare(feature.key)]!).filter(Boolean));
  for (const entry of classes) row(`${entry.name} (${subclassesOf(entry.key).map((sub) => sub.name).join(", ")})`, classEntries(entry));
  row("Feats", Object.values(FEAT_COVERAGE));
  row("Species traits", Object.values(SPECIES_COVERAGE));
  line();

  // Gaps
  const uses = new Map<GapCode, GapUse>();
  const note = (gaps: GapCode[] | undefined, owner: string, feature: string, level: number) => {
    for (const gap of gaps ?? []) {
      const use = uses.get(gap) ?? { classes: new Set<string>(), features: [], firstLevel: 99 };
      use.classes.add(owner);
      use.features.push(feature);
      use.firstLevel = Math.min(use.firstLevel, level);
      uses.set(gap, use);
    }
  };
  for (const entry of classes) {
    for (const owner of [entry, ...subclassesOf(entry.key)]) {
      for (const feature of owner.features) {
        note(CLASS_COVERAGE[bare(feature.key)]?.gaps, entry.name, `${feature.name} (${owner.name})`, feature.levels[0] ?? 99);
      }
    }
  }
  for (const feat of reference.feats) note(FEAT_COVERAGE[bare(feat.key)]?.gaps, "Feats", `${feat.name} (feat)`, 1);
  for (const species of reference.species) {
    for (const trait of species.traits) note(SPECIES_COVERAGE[speciesTraitKey(species.key, trait.name)]?.gaps, "Species", `${trait.name} (${species.name})`, 1);
  }
  line("## Gaps, most widespread first");
  line();
  line("Ranked by how many classes (and feats, species) need it, then by how early it's met. One engine change per gap");
  line("closes every feature it lists (plan Phase 7; weapon mastery is Phase 3).");
  line();
  line("| Gap | What's missing | Where | First level | Features |");
  line("|---|---|---|---|---|");
  const ranked = [...uses.entries()].sort(([codeA, a], [codeB, b]) =>
    b.classes.size - a.classes.size || a.firstLevel - b.firstLevel || b.features.length - a.features.length || codeA.localeCompare(codeB));
  for (const [code, use] of ranked) {
    line(`| \`${code}\` | ${cell(GAPS[code])} | ${[...use.classes].join(", ")} | ${use.firstLevel === 99 ? "—" : use.firstLevel} | ${cell(use.features.join("; "))} |`);
  }
  const unused = (Object.keys(GAPS) as GapCode[]).filter((code) => !uses.has(code));
  if (unused.length) {
    line();
    line(`Not used by any verdict: ${unused.map((code) => `\`${code}\``).join(", ")}.`);
  }
  line();

  // Per class
  for (const entry of classes) {
    for (const owner of [entry, ...subclassesOf(entry.key)]) {
      line(owner.subclassOf ? `### ${owner.name} (${entry.name} subclass)` : `## ${owner.name}`);
      line();
      line("| Level | Feature | Verdict | Gaps | Note |");
      line("|---|---|---|---|---|");
      for (const feature of owner.features) {
        const audit = CLASS_COVERAGE[bare(feature.key)];
        if (!audit) continue;
        const level = feature.levels.length ? feature.levels.join(", ") : "—";
        line(`| ${level} | ${cell(feature.name)} | ${audit.verdict} | ${gapList(audit.gaps)} | ${cell(audit.note ?? "")} |`);
      }
      line();
    }
  }

  line("## Feats");
  line();
  line("| Feat | Category | Verdict | Gaps | Note |");
  line("|---|---|---|---|---|");
  for (const feat of reference.feats) {
    const audit = FEAT_COVERAGE[bare(feat.key)];
    if (!audit) continue;
    line(`| ${cell(feat.name)} | ${feat.category} | ${audit.verdict} | ${gapList(audit.gaps)} | ${cell(audit.note ?? "")} |`);
  }
  line();

  line("## Species");
  line();
  line("| Species | Trait | Verdict | Gaps | Note |");
  line("|---|---|---|---|---|");
  for (const species of reference.species) {
    for (const trait of species.traits) {
      const audit = SPECIES_COVERAGE[speciesTraitKey(species.key, trait.name)];
      if (!audit) continue;
      line(`| ${species.name} | ${cell(trait.name)} | ${audit.verdict} | ${gapList(audit.gaps)} | ${cell(audit.note ?? "")} |`);
    }
  }
  line();

  line("## Backgrounds");
  line();
  line("All built by the builder: three abilities for +2 and +1 (or +1 to each), two skills and an origin feat. Tools and");
  line("equipment other than weapons and armor are outside a fight.");
  line();
  line("| Background | Abilities | Skills | Feat |");
  line("|---|---|---|---|");
  for (const background of reference.backgrounds) {
    line(`| ${background.name} | ${background.abilities.join(", ")} | ${background.skills.join(", ")} | ${cell(background.feat)} |`);
  }
  line();
  line("## Attribution");
  line();
  line(reference.attribution);
  return `${lines.join("\n")}\n`;
}
